# Generated by Django 4.2.1 on 2023-05-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Your Organistion', max_length=150)),
                ('abbreviation', models.CharField(help_text='Abbreviated form of Your Organistion', max_length=150)),
                ('mission', models.TextField(help_text="Your Organistion's Mission Statement")),
                ('vision', models.TextField(help_text='Vison Statement for Your Organistion')),
                ('slogan', models.CharField(help_text='Slogan of Your Organistion', max_length=150)),
                ('address', models.TextField(help_text='Street, City, P.O. Box for Your Organistion')),
                ('phone', models.CharField(help_text='Telephone Number of Your Organistion', max_length=15)),
                ('email', models.CharField(help_text='Email Address of Your Organistion', max_length=15)),
                ('facebook', models.URLField(blank=True, help_text="Your Organistion's Facebook Page", null=True)),
                ('twitter', models.URLField(blank=True, help_text="Your Organistion's Twitter Handle", null=True)),
                ('youtube', models.URLField(blank=True, help_text="Your Organistion's Youtube Chanel", null=True)),
                ('instagram', models.URLField(blank=True, help_text="Your Organistion's Instagram Account", null=True)),
                ('linkedin', models.URLField(blank=True, help_text="Your Organistion's LinkedIn link", null=True)),
                ('whatsapp', models.URLField(blank=True, help_text="Your Organistion's WhatsApp Contact", null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
