# Generated by Django 4.2.1 on 2023-05-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationsetup',
            name='email',
            field=models.CharField(help_text='Email Address of Your Organistion', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisationsetup',
            name='phone',
            field=models.CharField(help_text='Telephone Number of Your Organistion', max_length=100),
        ),
    ]
