# Generated by Django 4.2.1 on 2023-05-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_organisationsetup_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationsetup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
