services:
  - type: web
    name: apnwebapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn apnwebapp.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apnweb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
