# Generated by Django 4.2.1 on 2023-09-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('partnership', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartnershipPage',
            new_name='FormsPage',
        ),
    ]
