# Generated by Django 4.2.1 on 2023-09-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0005_rename_introduction_partnershippage_intro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=254)),
                ('partnership_type', models.CharField(choices=[('VOLUNTEER', 'VOLUNTEER'), ('FOUNDING PARTNER', 'FOUNDING PARTNER'), ('DONOR', 'DONOR')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='partnershippage',
            name='intro',
        ),
    ]
