# Generated by Django 4.2.1 on 2023-09-12 23:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('partnership', '0006_partner_remove_partnershippage_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(default='APN welcomes partners from different countries and ministries all over the world to support and facilitate the realization of its mission. Partnership is established by a longterm commitment to either financially support the mission, and/or volunteer skill/time for service. You can partner financially by subscribing for a periodic contribution and/or by volunteering your time and skills. ')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
