# Generated by Django 4.2.1 on 2023-09-13 12:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0009_remove_partnerspage_body_remove_partnerspage_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershippage',
            name='body',
            field=wagtail.fields.StreamField([('CTA', wagtail.blocks.StructBlock([('cta_button', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('pos', wagtail.blocks.IntegerBlock(max_value=4, min_value=1)), ('icon', wagtail.images.blocks.ImageChooserBlock(required=True)), ('action_name', wagtail.blocks.CharBlock(help_text="Enter intended action name .e.g. 'Make a Donation' ", required=True)), ('link_page', wagtail.blocks.PageChooserBlock(help_text='Selected the specific Page to go to', required=False))]), max_num=2, min_num=2))], template_name='partnership/partnership_page.html'))], use_json_field=True),
        ),
    ]
