# Generated by Django 4.2.1 on 2023-09-14 15:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0013_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnershippage',
            options={'verbose_name': 'Partnerships Page'},
        ),
        migrations.AlterField(
            model_name='partnershippage',
            name='body',
            field=wagtail.fields.StreamField([('CTA', wagtail.blocks.StructBlock([('cta_button', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('pos', wagtail.blocks.IntegerBlock(max_value=4, min_value=1)), ('icon', wagtail.images.blocks.ImageChooserBlock(required=True)), ('action_name', wagtail.blocks.CharBlock(help_text="Enter intended action name .e.g. 'Make a Donation' ", required=True)), ('link_page', wagtail.blocks.PageChooserBlock(help_text='Selected the specific Page to go to', required=False))]), max_num=2, min_num=2))]))], use_json_field=True),
        ),
    ]
