# Generated by Django 4.2.1 on 2023-05-15 14:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=150)), ('sub_heading', wagtail.blocks.CharBlock(max_length=150, required=False)), ('text_content', wagtail.blocks.RichTextBlock()), ('thumbnail', wagtail.images.blocks.ImageChooserBlock(required=False))]))], use_json_field=True),
        ),
    ]
