# Generated by Django 4.2.1 on 2023-09-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSetup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of Your Organistion', max_length=150)),
                ('abbreviation', models.CharField(help_text='Abbreviated form of Your Organistion', max_length=150)),
                ('mission', models.TextField(help_text="Your Organistion's Mission Statement")),
                ('vision', models.TextField(help_text='Vison Statement for Your Organistion')),
                ('slogan', models.CharField(help_text='Slogan of Your Organistion', max_length=150)),
                ('address', models.TextField(help_text='Street, City, P.O. Box for Your Organistion')),
                ('phone', models.CharField(help_text='Telephone Number of Your Organistion', max_length=100)),
                ('email', models.CharField(help_text='Email Address of Your Organistion', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(choices=[('twitter', 'twitter'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('whatsapp', 'whatsapp'), ('linkedin', 'linkedin')], help_text='Choose the media platform', max_length=255)),
                ('link', models.URLField(blank=True, help_text="Your Organistion's Social link", null=True)),
                ('handle', models.CharField(blank=True, help_text="Your Organistion's Social handle .e.g. @Agapepn", max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
    ]
