# Generated by Django 4.2.1 on 2023-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_pagebuttons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagebuttons',
            options={'verbose_name': 'Page Button', 'verbose_name_plural': 'Page Buttons'},
        ),
        migrations.RemoveField(
            model_name='pagebuttons',
            name='link_url',
        ),
        migrations.AddField(
            model_name='pagebuttons',
            name='link_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='link text'),
        ),
    ]
