# Generated by Django 4.2.1 on 2023-09-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_pagebuttons_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebuttons',
            name='icon_name',
            field=models.CharField(blank=True, default='gift', max_length=255, null=True, verbose_name='icon class name'),
        ),
    ]
