# Generated by Django 4.2.1 on 2023-09-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_pagebuttons_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebuttons',
            name='button_type',
            field=models.CharField(choices=[('donate', 'donate'), ('direction', 'direction'), ('volunteer', 'volunteer'), ('other', 'other')], help_text='Choose the Button type', max_length=255),
        ),
    ]
