# Generated by Django 4.2.1 on 2023-05-13 19:30

import content.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('AboutSection', wagtail.blocks.StructBlock([('MissionVisionImage', wagtail.images.blocks.ImageChooserBlock(required=True)), ('FoundingPartner', wagtail.blocks.StructBlock([('full_names', wagtail.blocks.CharBlock(help_text="Enter Founding partner's name.", required=True)), ('partnership_type', wagtail.blocks.CharBlock(help_text='Partnership position/type.', required=True)), ('background', content.blocks.RichtextBlock()), ('twitter', wagtail.blocks.URLBlock(help_text='Enter your Twitter social media link')), ('facebook', wagtail.blocks.URLBlock(help_text='Enter your Facebook social media link')), ('instagram', wagtail.blocks.URLBlock(help_text='Enter your Instagram social media link'))])), ('Adblock', wagtail.blocks.StructBlock([('statement', content.blocks.RichtextBlock()), ('donation_link', wagtail.blocks.StructBlock([('button_page', wagtail.blocks.PageChooserBlock(help_text='If selected, this url will be used first', label='Link to an internal page', required=False)), ('button_url', wagtail.blocks.URLBlock(help_text='If added, this url will be used secondarily to the button page', label='Link to an external web page', required=False))], label='Donation Link')), ('volunteer_button', wagtail.blocks.PageChooserBlock(help_text='If selected, this url will be used first', required=True))]))]))], use_json_field=True),
        ),
    ]
