# Generated by Django 4.2.1 on 2023-09-11 14:18

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('welcome', wagtail.blocks.StructBlock([('action_block', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('pos', wagtail.blocks.IntegerBlock(max_value=4, min_value=1)), ('icon', wagtail.images.blocks.ImageChooserBlock(required=True)), ('action_name', wagtail.blocks.CharBlock(help_text="Enter intended action name .e.g. 'Make a Donation' ", required=True)), ('link_page', wagtail.blocks.PageChooserBlock(help_text='Selected the specific Page to go to', required=True))]), max_num=4, min_num=0))]))], use_json_field=True),
        ),
    ]
