# Generated by Django 4.2.1 on 2023-08-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_remove_flexpage_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Service Page', 'verbose_name_plural': 'Service Page'},
        ),
    ]
