# Generated by Django 4.1.7 on 2023-05-01 16:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menu_items', wagtail.fields.StreamField([('external_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock()), ('children', wagtail.blocks.StreamBlock([('external_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock())])), ('page_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock())]))]))])), ('page_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('children', wagtail.blocks.StreamBlock([('external_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock())])), ('page_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock())]))]))]))], use_json_field=None)),
            ],
        ),
        migrations.CreateModel(
            name='PageWithNavbar',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.navbar')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
