# Generated by Django 4.1.7 on 2023-05-01 16:34

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='menu_items',
            field=wagtail.fields.StreamField([('external_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock()), ('children', wagtail.blocks.StreamBlock([('external_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock())])), ('page_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock())]))]))])), ('page_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('children', wagtail.blocks.StreamBlock([('external_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock())])), ('page_link', wagtail.blocks.StructBlock([('display_text', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock())]))]))]))], use_json_field=True),
        ),
    ]
